name: BaugRPG
version: 1.0
author: BaugIndustries
main: org.baugindustries.baugrpg.Main
api-version: 1.17
description: A performance enhancing plugin that has absolutely no LOTR rpg elements dont check.
depend: [ProtocolLib]

commands:
  resetrace:
   aliases: [rr]
   usage: /resetrace, /rr
   description: This resets race for debugging purposes
   permission: minecraft.command.op
  setrace:
   aliases: [sr]
   usage: /setrace, /sr
   description: This sets race if you clicked out of the race selection menu
  chat:
   usage: /chat <Channel>
   description: Change which chat channel you are in
  racewizard:
   usage: /racewizard
   aliases: [rw]
   description: Assigns you to the wizard race (Op only)
   permission: minecraft.command.op
  baugscroll:
   usage: /baugscroll, /scrollsofbaug, /bs, /sb
   aliases: [bs, scrollsofbaug, sb]
   description: Opens a hub menu that will give you any and all information you need to know to play on a BaugRPG server
  tpa:
   usage: /tpa <Player>, /tpask <Player>
   aliases: [tpask]
   description: Requests to teleport to another player
  tphere:
   usage: /tphere <Player>, /tph <Player>, /tpahere <Player>
   aliases: [tph, tpahere]
   description: Requests another player teleport to you.
  tpaccept:
   usage: /tpaccept, /tpayes, /tpyes
   aliases: [tpayes, tpyes]
   description: Accepts a teleport request.
  tpdeny:
   usage: /tpdeny, /tpno, /tpano
   aliases: [tpno, tpano]
   description: Denys a teleport request.
  balance:
   usage: /balance, /bal, /wallet
   aliases: [bal, wallet]
   description: Displays your balance.
  pay:
   usage: /pay <Player> <Amount>
   description: Pays another player a certain amount of dwarven gold.
  bankbal:
   usage: /bankbal
   description: Shows the amount of dwarven gold in the bank.
  withdraw:
   usage: /withdraw <Amount>
   description: Withdraws amount of dwarven gold from the bank and puts it in your wallet.
  deposit:
   usage: /deposit <Amount>
   description: Deposits amount of dwarven gold from your wallet and puts it in the bank.
  setbal:
   usage: /setbal <Player> <Amount>
   description: Sets the amount of dwarven gold in a players wallet.
  setpoi:
   usage: /setpoi <poi>
   description: Sets a point of interest used to teleport players to on certain events. Required for plugin use.
   permission: minecraft.command.op
  warp:
   usage: /warp <Location>
   description: Warp to important locations in the world.
  warpaccept:
   usage: /warpaccept
   description: Accept a teleport request from a player.
  spawn:
   usage: /spawn
   description: Teleports you to your race's spawn.
  chunkclaim:
   usage: /chunkclaim <Radius>
   description: Claims the chunks around the one you're standing in.
   aliases: [cc]
  map:
   usage: /map
   description: Displays a map of nearby chunks.
  claim:
   usage: /claim, /claim delete, /claim trust <Player>, /claim untrust <Player>
   description: Controls various aspects around claiming.